version: '3.5'
services:
  api1: # API - Instância 01
    image: teohen/rinha-de-backend
    hostname: api1
    environment:
      - HTTP_PORT=8081
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinhadebackend
      - DB_PORT=5432
    depends_on:
        - postgres
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'


  api2: # API - Instância 01
    image: teohen/rinha-de-backend
    hostname: api2
    depends_on:
      - postgres
    network_mode: "host"
    environment:
      - HTTP_PORT=8082
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinhadebackend
      - DB_PORT=5432
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'


  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2

    network_mode: "host"

    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  postgres: # Banco de dados
    image: postgres:latest
    container_name: postgres-rinha-de-backend
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinhadebackend
      POSTGRES_HOST_AUTH_METHOD: "trust"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
